#*****************************************************************************************
# create_vitis_project.tcl
#
# Creates a Vitis workspace with:
#   1. A platform project from the exported XSA
#   2. A standalone application project with sources from vitis/src/
#
# Usage (from XSCT console or batch mode):
#   xsct /path/to/Zedboard-OS-Lab/vitis/create_vitis_project.tcl
#
# Or in batch mode from a terminal:
#   xsct create_vitis_project.tcl
#
# Requires: vitis/zed_os_fpga.xsa (generated by build.tcl)
#*****************************************************************************************

set script_dir [file dirname [info script]]
set origin_dir [file normalize "$script_dir/.."]

set xsa_file  [file normalize "$origin_dir/vitis/zed_os_fpga.xsa"]
set workspace [file normalize "$origin_dir/vitis/workspace"]
set src_dir   [file normalize "$origin_dir/vitis/src"]

# Validate XSA exists
if { ![file isfile $xsa_file] } {
    error "ERROR: XSA file not found at $xsa_file\nRun build.tcl in Vivado first."
}

# Set workspace
setws $workspace

# Step 1: Create platform project from XSA
puts "INFO: Creating platform project..."
platform create -name zed_os_fpga_platform \
    -hw $xsa_file \
    -os standalone \
    -proc ps7_cortexa9_0

platform write
platform active zed_os_fpga_platform
platform generate

# Step 2: Create application project
puts "INFO: Creating application project..."
app create -name zed_os_fpga_app \
    -platform zed_os_fpga_platform \
    -domain standalone_ps7_cortexa9_0 \
    -template {Empty Application(C++)}

# Step 3: Add sources from vitis/src (app and driver files)
puts "INFO: Adding source files..."
foreach src_file [glob -nocomplain "$src_dir/app/*" "$src_dir/drv/*"] {
    importsources -name zed_os_fpga_app -path $src_file -linker-script 0
    puts "  Added: [file tail $src_file]"
}

# Step 4: Build the application
puts "INFO: Building application..."
app build -name zed_os_fpga_app

puts "INFO: Vitis project created at $workspace"
puts "INFO: Open Vitis and set workspace to $workspace to view the project."
