#*****************************************************************************************
# create_vitis_project.tcl
#
# Creates a Vitis workspace with:
#   1. A platform project from the exported XSA
#   2. A standalone application project with sources from vitis/src/
#
# Usage (from XSCT console or batch mode):
#   xsct /path/to/Zedboard-OS-Lab/vitis/create_vitis_project.tcl
#   xsct /path/to/Zedboard-OS-Lab/vitis/create_vitis_project.tcl --skip-platform
#
# Arguments:
#   --skip-platform   Skip platform creation (use if platform already exists in workspace)
#
# Requires: vitis/zed_os_fpga.xsa (generated by build.tcl)
#*****************************************************************************************

set script_dir [file dirname [info script]]
set origin_dir [file normalize "$script_dir/.."]

set xsa_file  [file normalize "$origin_dir/vitis/zed_os_fpga.xsa"]
set workspace [file normalize "$origin_dir/vitis/workspace"]
set src_dir   [file normalize "$origin_dir/vitis/src"]

# Parse arguments
set skip_platform 0
if { [lsearch $argv "--skip-platform"] >= 0 } {
    set skip_platform 1
}

# Set workspace
setws $workspace

# Step 1: Create platform project from XSA
if { $skip_platform } {
    puts "INFO: Skipping platform creation (--skip-platform specified)"
    platform active zed_os_fpga_platform
} else {
    # Validate XSA exists before attempting platform creation
    if { ![file isfile $xsa_file] } {
        error "ERROR: XSA file not found at $xsa_file\nRun build.tcl in Vivado first."
    }
    puts "INFO: Creating platform project..."
    platform create -name zed_os_fpga_platform \
        -hw $xsa_file \
        -os standalone \
        -proc ps7_cortexa9_0

    platform write
    platform active zed_os_fpga_platform
    platform generate
}

# Step 2: Create application project
# Domain name is 'standalone_domain' (created by platform create above)
# Template is 'Empty Application(C)' - Vitis 2022.1 has no separate C++ template;
# .cpp source files are compiled as C++ regardless of the template used.
puts "INFO: Creating application project..."
if { [catch {app list} app_list] == 0 && [lsearch $app_list "zed_os_fpga_app"] >= 0 } {
    puts "INFO: Removing existing application project..."
    app remove zed_os_fpga_app
}
app create -name zed_os_fpga_app \
    -platform zed_os_fpga_platform \
    -domain standalone_domain \
    -template {Empty Application(C)}

# Step 3: Add sources from vitis/src (app and driver files)
puts "INFO: Adding source files..."
foreach src_file [glob -nocomplain "$src_dir/app/*" "$src_dir/drv/*"] {
    importsources -name zed_os_fpga_app -path $src_file
    puts "  Added: [file tail $src_file]"
}

# Step 4: Build the application
puts "INFO: Building application..."
app build -name zed_os_fpga_app

puts "INFO: Vitis project created at $workspace"
puts "INFO: Open Vitis and set workspace to $workspace to view the project."
